# Generated by Django 4.1.4 on 2022-12-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_empleado_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='id',
            new_name='idEmpleado',
        ),
    ]
