# Generated by Django 4.1.4 on 2022-12-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_cliente_contacto_detallepedido_maquina_modelo_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idPedido',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
