# Generated by Django 4.1.4 on 2022-12-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_pedido_id_alter_pedido_idpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='otros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
