# Generated by Django 4.1.4 on 2022-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_maquina_otros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ns',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
