# Generated by Django 4.1.4 on 2022-12-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_empleado_ns_alter_empleado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(choices=[('Trabajador', 'Trabajador'), ('Encargado', 'Encargado'), ('Administrador', 'Administrador')], default='Trabajador', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ns',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('Tejido', 'Tejido'), ('Corte', 'Corte'), ('Plancha', 'Plancha'), ('Empaque', 'Empaque'), ('Transporte', 'Transporte'), ('Diseno', 'Diseño'), ('Gerencia', 'Gerencia')], default='Tejido', max_length=20),
        ),
    ]
